Cde dev learning 1
Unosquare-CoE-JavaScript/yair-santiago pull request #1
Opened 2022-02-22 00:56 UTC by unoyira

I finished the full book of YDKJSY. 
In this PR I include the notes I took along with the exercises from the last section.

2022-02-22 15:32 UTC, lnaranjo approved these changes

2022-02-22 15:34 UTC, lnaranjo requested changes
Can you please create a folder for YDKJSY book and include the md files in it?

2022-02-22 15:59 UTC, unoyira commented
Do I rename the existing one or create it inside the existing one?

2022-02-23 16:01 UTC, lnaranjo approved these changes

2022-02-23 16:01 UTC, merged